stages:
  - test
  - deploy

services:
  - postgres:latest
  - docker:19.03.1-dind

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust
  DOCKER_TLS_CERTDIR: "/certs"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test:
  image: node:12.18-alpine
  stage: test
  script:
    - npm install
    - npm test
    - mv coverage/Icov-report/ public/
  artifacts:
    paths:
      - public


build:
  stage: deploy
  image: docker:19.03.1
  script:
    - docker login $REGISTARY_DOMAIN -u $DOCKER_REGISTARY_USER -p $DOCKER_REGISTARY_PASS
    - docker build -t $REGISTARY_DOMAIN/barlerer/url-shortner .
    - docker push $REGISTARY_DOMAIN/barlerer/url-shortner


