version: "3.8"
services:
    app:
        build: .
        depends_on:
        - postgres
        ports:
        - 4000:4000

    postgres:
        image: postgres:alpine
        ports:
        - 5432:5432
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres